/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameIndexRouteImport } from './routes/$username.index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists.$playlistId'
import { Route as UsernameChannelRouteImport } from './routes/$username.$channel'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameRoute,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameChannelRoute = UsernameChannelRouteImport.update({
  id: '/$channel',
  path: '/$channel',
  getParentRoute: () => UsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/$username/$channel': typeof UsernameChannelRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/$username/': typeof UsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/$username/$channel': typeof UsernameChannelRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/$username': typeof UsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/$username/$channel': typeof UsernameChannelRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/$username/': typeof UsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/dashboard'
    | '/search'
    | '/settings'
    | '/upload'
    | '/$username/$channel'
    | '/playlists/$playlistId'
    | '/watch/$videoId'
    | '/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/search'
    | '/settings'
    | '/upload'
    | '/$username/$channel'
    | '/playlists/$playlistId'
    | '/watch/$videoId'
    | '/$username'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/dashboard'
    | '/search'
    | '/settings'
    | '/upload'
    | '/$username/$channel'
    | '/playlists/$playlistId'
    | '/watch/$videoId'
    | '/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof UsernameRoute
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$channel': {
      id: '/$username/$channel'
      path: '/$channel'
      fullPath: '/$username/$channel'
      preLoaderRoute: typeof UsernameChannelRouteImport
      parentRoute: typeof UsernameRoute
    }
  }
}

interface UsernameRouteChildren {
  UsernameChannelRoute: typeof UsernameChannelRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernameChannelRoute: UsernameChannelRoute,
  UsernameIndexRoute: UsernameIndexRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRouteWithChildren,
  DashboardRoute: DashboardRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
